# 6th October 2019

In [1]:
import numpy as np
arr3d = np.array([[[1,2,3],[4,5,6]],[[4,5,6],[7,9,10]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 4,  5,  6],
        [ 7,  9, 10]]])

In [2]:
arr3d.reshape((2,3,2))

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 4,  5],
        [ 6,  7],
        [ 9, 10]]])

In [3]:
arr3d.transpose()

array([[[ 1,  4],
        [ 4,  7]],

       [[ 2,  5],
        [ 5,  9]],

       [[ 3,  6],
        [ 6, 10]]])

In [4]:
arr3d.ravel()

array([ 1,  2,  3,  4,  5,  6,  4,  5,  6,  7,  9, 10])

In [5]:
arr3d.nonzero()

(array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1], dtype=int64),
 array([0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))

In [6]:
arr3d == 2
arr3d.any()

True

In [8]:
o = arr3d < 10
o.all()

False

In [9]:
print(o)

[[[ True  True  True]
  [ True  True  True]]

 [[ True  True  True]
  [ True  True False]]]


In [10]:
even = arr3d%2==0
even.any()

True

In [12]:
arr3d[o]

array([1, 2, 3, 4, 5, 6, 4, 5, 6, 7, 9])

In [16]:
jungle = np.array(["lion","tiger","hyena","lion","deer","monkey"])
w = jungle=="donkey"
s = jungle=="lion"
print(s.sum())
print(w.any())

2
False


In [17]:
np.unique(jungle)

array(['deer', 'hyena', 'lion', 'monkey', 'tiger'], dtype='<U6')

In [18]:
np.save("data.npy",jungle)

In [20]:
np.load("data.npy")

array(['lion', 'tiger', 'hyena', 'lion', 'deer', 'monkey'], dtype='<U6')

In [53]:
np.random.randn(4,4)

array([[-2.60121062, -0.1968244 ,  1.87855887,  2.31355622],
       [ 1.81383259,  1.42519242,  0.28315128,  1.21912806],
       [ 1.14084968,  0.36023614,  0.81666146, -0.73076784],
       [-1.05599162, -0.0142745 , -1.09053489,  0.20302304]])

In [35]:
n = np.arange(1,11)
e = np.arange(2,11,2)
m = np.arange(3,11,3)

In [36]:
n 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [37]:
m

array([3, 6, 9])

In [38]:
e

array([ 2,  4,  6,  8, 10])

In [39]:
n.reshape((5,2))

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [40]:
np.savez("data1.npz",m1 = m,n1 = n,e1 = e)


In [42]:
p = np.load("data1.npz","r")
p["m1"]

array([3, 6, 9])

In [46]:
print(list(p.keys()))

['m1', 'n1', 'e1']


In [47]:
print(list(p.values()))

[array([3, 6, 9]), array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]), array([ 2,  4,  6,  8, 10])]


In [58]:
y = np.array([[1,2,3],[4,5,6],[7,8,9]])
y

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [59]:
y.trace()

15

In [60]:
print(np.linalg.det(y))

-9.51619735392994e-16


In [61]:
print(np.linalg.eig(y))

(array([ 1.61168440e+01, -1.11684397e+00, -9.75918483e-16]), array([[-0.23197069, -0.78583024,  0.40824829],
       [-0.52532209, -0.08675134, -0.81649658],
       [-0.8186735 ,  0.61232756,  0.40824829]]))


Psuedo Random Number Generation

In [69]:
y = np.random.gamma(shape=(2,2))
y

array([0.43535785, 1.96267961])

In [85]:
np.random.seed(1) #fix the random values 


In [86]:
np.random.randn(5)

array([ 1.62434536, -0.61175641, -0.52817175, -1.07296862,  0.86540763])

In [97]:
np.random.uniform(1,5) #floating point number

4.202978274702147

In [98]:
fr = np.random.gamma(shape=(4,10))
fr

array([6.29433626, 6.63436869])

In [100]:
j = np.random.randn(100,5)
j

array([[-8.08847196e-01,  5.57439453e-01,  1.81038744e-01,
         1.10717545e+00,  1.44287693e+00],
       [-5.39681562e-01,  1.28376990e-01,  1.76041518e+00,
         9.66539250e-01,  7.13049050e-01],
       [ 1.30620607e+00, -6.04602969e-01,  6.36583409e-01,
         1.40925339e+00,  1.62091229e+00],
       [-8.06184817e-01, -2.51674208e-01,  3.82715174e-01,
        -2.88997343e-01, -3.91816240e-01],
       [ 6.84001328e-01, -3.53409983e-01, -1.78791289e+00,
         3.61847316e-01, -4.24492791e-01],
       [-7.31530982e-01, -1.56573815e+00,  1.01382247e+00,
        -2.22711263e+00, -1.69933360e+00],
       [-2.75846063e-01,  1.22895559e+00,  1.30970591e+00,
        -1.15498263e+00, -1.77632196e-01],
       [-1.51045638e+00,  1.01120706e+00, -1.47656266e+00,
        -1.43195745e-01,  1.03298378e+00],
       [-2.22414029e-01,  1.47016034e+00, -8.70008223e-01,
         3.69190470e-01,  8.53282186e-01],
       [-1.39711730e-01,  1.38631426e+00,  5.48129585e-01,
        -1.63744959e+00

In [101]:
j.reshape(1,-1)

array([[-8.08847196e-01,  5.57439453e-01,  1.81038744e-01,
         1.10717545e+00,  1.44287693e+00, -5.39681562e-01,
         1.28376990e-01,  1.76041518e+00,  9.66539250e-01,
         7.13049050e-01,  1.30620607e+00, -6.04602969e-01,
         6.36583409e-01,  1.40925339e+00,  1.62091229e+00,
        -8.06184817e-01, -2.51674208e-01,  3.82715174e-01,
        -2.88997343e-01, -3.91816240e-01,  6.84001328e-01,
        -3.53409983e-01, -1.78791289e+00,  3.61847316e-01,
        -4.24492791e-01, -7.31530982e-01, -1.56573815e+00,
         1.01382247e+00, -2.22711263e+00, -1.69933360e+00,
        -2.75846063e-01,  1.22895559e+00,  1.30970591e+00,
        -1.15498263e+00, -1.77632196e-01, -1.51045638e+00,
         1.01120706e+00, -1.47656266e+00, -1.43195745e-01,
         1.03298378e+00, -2.22414029e-01,  1.47016034e+00,
        -8.70008223e-01,  3.69190470e-01,  8.53282186e-01,
        -1.39711730e-01,  1.38631426e+00,  5.48129585e-01,
        -1.63744959e+00,  3.95860270e+00,  6.48643644e-0

In [102]:
d = np.array([[3,5,7],[7,8,4]])
d

array([[3, 5, 7],
       [7, 8, 4]])

In [103]:
d.ravel()

array([3, 5, 7, 7, 8, 4])

In [104]:
d.flatten()

array([3, 5, 7, 7, 8, 4])

In [105]:
d[0] = -1


In [107]:
d.ravel()

array([-1, -1, -1,  7,  8,  4])

In [109]:
l = d.ravel()
print(l)

[-1 -1 -1  7  8  4]


In [ ]:
#axis = 1 , Column increase
#axis = 0 , Row increase


In [135]:
z = np.arange(1,10).reshape(3,3)
b = np.arange(1,10).reshape(3,3)

In [136]:
print(z)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [137]:
print(z,"\n\n",b)

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [141]:
np.concatenate((z,b), axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6],
       [7, 8, 9, 7, 8, 9]])

In [122]:
u = np.arange(1,13).reshape(4,3)
t = np.arange(1,21).reshape(4,5)
print(u,"\n\n",t)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] 

 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [125]:
np.concatenate((u,t), axis=1)

array([[ 1,  2,  3,  1,  2,  3,  4,  5],
       [ 4,  5,  6,  6,  7,  8,  9, 10],
       [ 7,  8,  9, 11, 12, 13, 14, 15],
       [10, 11, 12, 16, 17, 18, 19, 20]])

In [139]:
np.vstack((z,u))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [140]:
np.hstack((z,b))

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6],
       [7, 8, 9, 7, 8, 9]])

SPliting in Array

In [142]:
q = np.array([[1,2,3,4,5],[6,7,8,9,10]])
q

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [148]:
k = np.split(q,[3],axis=1)

In [149]:
k

[array([[1, 2, 3],
        [6, 7, 8]]), array([[ 4,  5],
        [ 9, 10]])]

In [150]:
k[0]

array([[1, 2, 3],
       [6, 7, 8]])

In [152]:
k[1]

array([[ 4,  5],
       [ 9, 10]])