# 29th September 2019

Revision of Class01

{Indexing and Slicing}

In [2]:
import numpy as np

muneermohsin558@gmail.com

In [3]:
arr1 = np.array([2,4,6,8,10,12,14])


In [4]:
arr1[4]

10

In [9]:
arr1[2:3]

array([6])

In [11]:
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [12]:
arr2[2]

array([7, 8, 9])

In [13]:
arr2[1,2]

6

In [14]:
arr2[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
arr2[0][2]

3

In [18]:
arr3d = np.array([[[1,2,3],[4,5,6]],[[4,5,6],[7,9,10]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 4,  5,  6],
        [ 7,  9, 10]]])

In [19]:
arr3d.shape

(2, 2, 3)

In [20]:
arr3d.reshape(1,4,3)

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 4,  5,  6],
        [ 7,  9, 10]]])

In [22]:
arr3d.reshape(2,3,2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 4,  5],
        [ 6,  7],
        [ 9, 10]]])

In [23]:
list_1 = range(1000) 

In [28]:
%time for i in list_1:  i * 3
list_1

Wall time: 0 ns


range(0, 1000)

In [29]:
list_2 = np.arange(1000)


In [30]:
%time list_2*3

Wall time: 1 ms


array([   0,    3,    6,    9,   12,   15,   18,   21,   24,   27,   30,
         33,   36,   39,   42,   45,   48,   51,   54,   57,   60,   63,
         66,   69,   72,   75,   78,   81,   84,   87,   90,   93,   96,
         99,  102,  105,  108,  111,  114,  117,  120,  123,  126,  129,
        132,  135,  138,  141,  144,  147,  150,  153,  156,  159,  162,
        165,  168,  171,  174,  177,  180,  183,  186,  189,  192,  195,
        198,  201,  204,  207,  210,  213,  216,  219,  222,  225,  228,
        231,  234,  237,  240,  243,  246,  249,  252,  255,  258,  261,
        264,  267,  270,  273,  276,  279,  282,  285,  288,  291,  294,
        297,  300,  303,  306,  309,  312,  315,  318,  321,  324,  327,
        330,  333,  336,  339,  342,  345,  348,  351,  354,  357,  360,
        363,  366,  369,  372,  375,  378,  381,  384,  387,  390,  393,
        396,  399,  402,  405,  408,  411,  414,  417,  420,  423,  426,
        429,  432,  435,  438,  441,  444,  447,  4

In [39]:
list_3 = range(10000)
list_4 = range(10000)
%time for i in range(0,len(list_3)): r = list_3[i] + list_4[i]    

Wall time: 5.99 ms


In [38]:
k = np.arange(10000)
l = np.arange(10000)
%time k + l 

Wall time: 0 ns


array([    0,     2,     4, ..., 19994, 19996, 19998])

In [2]:
#Task01
import numpy as np
w = np.zeros((2,3,4))
w.astype("int32")

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [4]:
#Task05
a = np.array([2, 3.2, 5.5, -6.4, -2.2, 2.4])
a

array([ 2. ,  3.2,  5.5, -6.4, -2.2,  2.4])

In [5]:
#Task06
a[1]

3.2

In [6]:
a[1:4]

array([ 3.2,  5.5, -6.4])

In [21]:
b = np.array([[5, 6, 7, 8],[1, 2, 3, 4],[5, 6, 7, 8],[1, 2, 3, 4]])
b

array([[5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4]])

In [22]:
b.shape

(4, 4)

In [23]:
a[:3]

array([2. , 3.2, 5.5])

In [24]:
b[0:2,0:3]

array([[5, 6, 7],
       [1, 2, 3]])

In [25]:
b[:,2]

array([7, 3, 7, 3])