# Date: 22th September 2019

# Topic: NumPy And Its Attributes

- Linguo Franca for exchange
- Data Exchange Library
- Numeric Python 
- invented 2005 by Travis Oliphent
- Consists of Array
- Operations on arrays fastly
- Read/Write array data
- Linear algebra operations (Eigen Values, Matrices)
- C language integration withv NumPy

In [2]:
import numpy as np 

In [2]:
a= np.arange(1000)
%time a*3

Wall time: 0 ns


array([   0,    3,    6,    9,   12,   15,   18,   21,   24,   27,   30,
         33,   36,   39,   42,   45,   48,   51,   54,   57,   60,   63,
         66,   69,   72,   75,   78,   81,   84,   87,   90,   93,   96,
         99,  102,  105,  108,  111,  114,  117,  120,  123,  126,  129,
        132,  135,  138,  141,  144,  147,  150,  153,  156,  159,  162,
        165,  168,  171,  174,  177,  180,  183,  186,  189,  192,  195,
        198,  201,  204,  207,  210,  213,  216,  219,  222,  225,  228,
        231,  234,  237,  240,  243,  246,  249,  252,  255,  258,  261,
        264,  267,  270,  273,  276,  279,  282,  285,  288,  291,  294,
        297,  300,  303,  306,  309,  312,  315,  318,  321,  324,  327,
        330,  333,  336,  339,  342,  345,  348,  351,  354,  357,  360,
        363,  366,  369,  372,  375,  378,  381,  384,  387,  390,  393,
        396,  399,  402,  405,  408,  411,  414,  417,  420,  423,  426,
        429,  432,  435,  438,  441,  444,  447,  4

In [3]:
b = np.zeros((2,2))
b

array([[0., 0.],
       [0., 0.]])

In [4]:
c = np.ones((3,3))
c

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [5]:
d = c * 4
d

array([[4., 4., 4.],
       [4., 4., 4.],
       [4., 4., 4.]])

In [6]:
e = [7,9,8,1,3,4]
np.array(e)

array([7, 9, 8, 1, 3, 4])

In [7]:
f1 = np.arange(100,1,-1)
f2 = np.arange(2,100,2)
f3 = np.arange(1,100,2)
print("f1 = ",f1,"\n\nf2 = ",f2,"\n\nf3 = ",f3)

f1 =  [100  99  98  97  96  95  94  93  92  91  90  89  88  87  86  85  84  83
  82  81  80  79  78  77  76  75  74  73  72  71  70  69  68  67  66  65
  64  63  62  61  60  59  58  57  56  55  54  53  52  51  50  49  48  47
  46  45  44  43  42  41  40  39  38  37  36  35  34  33  32  31  30  29
  28  27  26  25  24  23  22  21  20  19  18  17  16  15  14  13  12  11
  10   9   8   7   6   5   4   3   2] 

f2 =  [ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48
 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94 96
 98] 

f3 =  [ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]


In [8]:
f4 = np.arange(7,71,7)
print("f4 = ",f4)

f4 =  [ 7 14 21 28 35 42 49 56 63 70]


In [3]:
g = np.empty((4,4)) #random number array
g

array([[4.67296746e-307, 1.69121096e-306, 6.23058707e-307,
        8.45593934e-307],
       [7.56593017e-307, 1.11258854e-306, 1.60218491e-306,
        1.11261095e-306],
       [8.06639778e-308, 6.23038336e-307, 6.23058028e-307,
        1.11260348e-306],
       [1.37962049e-306, 2.22521238e-306, 1.24611470e-306,
        2.22507386e-306]])

# Attributes Of NumPy Array

- shape (for shape of array)
- dtype (for data-types of elements)
- ndim (for number of dimensions)

In [10]:
b.shape

(2, 2)

In [11]:
c.shape

(3, 3)

In [12]:
c.dtype

dtype('float64')

In [13]:
c.astype("int32")

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [14]:
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)
print(f1.ndim)

1
2
2
2
1


In [25]:
h = np.array([[2,3,4,5],[7,8,9,10],[2,4,6,8]])
print(h)
print("\n",h.reshape((4,3)))
print("\n",h.reshape((2,6)))
print("\n",h.reshape((6,2)))

[[ 2  3  4  5]
 [ 7  8  9 10]
 [ 2  4  6  8]]

 [[ 2  3  4]
 [ 5  7  8]
 [ 9 10  2]
 [ 4  6  8]]

 [[ 2  3  4  5  7  8]
 [ 9 10  2  4  6  8]]

 [[ 2  3]
 [ 4  5]
 [ 7  8]
 [ 9 10]
 [ 2  4]
 [ 6  8]]


# Vectorization

- Batch Operators without writing for loops 
- Any arithematic operation applies element-wise
- Arithematic operation with Scalar propagate the scalar argument to each element in an array
- Comparison between array of same size yields Boolean array
- Operation between differently sized arrays is called Broadcasting

In [26]:
1/f4

array([0.14285714, 0.07142857, 0.04761905, 0.03571429, 0.02857143,
       0.02380952, 0.02040816, 0.01785714, 0.01587302, 0.01428571])

In [27]:
f4*2

array([ 14,  28,  42,  56,  70,  84,  98, 112, 126, 140])

In [32]:
i = np.array([[1,2,1,4],[8,4,6,1],[0,5,3,1]])
print(h,"\n\n",i)
print("\n\n",h+i)

[[ 2  3  4  5]
 [ 7  8  9 10]
 [ 2  4  6  8]] 

 [[1 2 1 4]
 [8 4 6 1]
 [0 5 3 1]]


 [[ 3  5  5  9]
 [15 12 15 11]
 [ 2  9  9  9]]


In [33]:
f2>6

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True])

In [34]:
f2[f2>20]

array([22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54,
       56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88,
       90, 92, 94, 96, 98])

In [35]:
f3[f3<9]

array([1, 3, 5, 7])

In [38]:
names = np.array(["Salman","Uzaif","Nabeel","Haseeb","Talha"])
fee = np.array(["submitted","submitted","unsubmitted","submitted","unsubmitted"])
course = np.array(["A.I","C.C","IOT","C.C","IOT"])
print(names[fee=="submitted"])
print(names[course=="C.C"])

['Salman' 'Uzaif' 'Haseeb']
['Uzaif' 'Haseeb']


In [44]:
j = np.zeros((10,10))
j.astype("int32")

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [46]:
j[0,:] = 1
j[9,:] = 1
j[:,0] = 1
j[:,9] = 1
print(j.astype("int32"))

[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


In [49]:
k = np.zeros((10,10))
k.astype("int32")
k[1:-1,1:-1] = 1
k

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])